### ISSUE TITLE
Seems when I load focus, it kills customize-faces

### ISSUE THREAD

**Issue by Atman50** [larstvei/Focus#10]
I don't know why, but I finally tracked down some broken modes (like customize-faces, but C-x C-c which normally exits for me also gets broken).

I included focus with 

``` elisp
(use-package focus :ensure t)
```

Not entirely sure why so I thought I'd report it. It was the most recent melpa version: 20161013.401

Feel free to close this although I would love to use the functionality, I don't have the time to figure out the interesting interaction with my other commands...

**Comment by larstvei** [comment]
Hi, thanks for reporting!

Could you perhaps provide a link to your configuration file? If so, I'll might be able to track down the bug. Without it I'm not able to reproduce it, which makes it difficult to debug.

**Comment by Atman50** [comment]
https://github.com/Atman50/emacs-config.git

I commented out the focus inclusion.

Let me know if I can help out at all.

**Comment by Atman50** [comment]
BTW, this on emacs-25.1.1 CentOS Linux release 7.2.1511.

Nothing else seems to interact like this.

**Comment by larstvei** [comment]
Thanks, I'll look into this as soon as I find the time!

**Comment by larstvei** [comment]
Hi, sorry for being slow on this one. I was not able to reproduce the error easily, but another issue has led me to what I suspect is the problem here as well. I still have to find a way to mend the issue without breaking a feature in `focus-mode`, but expect to have this sorted out soon!

**Comment by Atman50** [comment]
No worries and no need to apologize. When you get a fix, I'd be happy to give it a try.

**Comment by larstvei** [comment]
Does the current master branch resolve your problem?

**Comment by larstvei** [comment]
@Atman50, can you check if ffd97a5 fixed the issue?
