### ISSUE TITLE
It only works in soft-wrapped text

### ISSUE THREAD

**Issue by mrbig033** [larstvei/Focus#17]
I have the habit of formatting my text on Evil mode using the command "gwap" (evil-fill), and Focus does not recognize these paragraphs, even though there are blank lines between them.

**Comment by larstvei** [comment]
Hi!

Can you provide an example? Does it work if you use Emacs' built-in `fill-paragraph`?

I doubt that Evil mode has anything to do with it, as Focus only cares about the text around the cursor.

**Comment by larstvei** [comment]
Closing because I can't reproduce.
