### ISSUE TITLE
Adding package to NonGNU ELPA

### ISSUE THREAD

**Issue by phikal** [larstvei/Focus#25]
Hi, would there be any interest in adding Focus to [NonGNU ELPA](https://elpa.nongnu.org/)?  That would allow for it to be installed without any further configuration from Emacs 28 onwards.

**Comment by larstvei** [comment]
Hi, sorry for a late reply.

Yes, it would be great to see the package on NonGNU ELPA. It is pretty stable, as the only feature I would like to add is currently stuck do to potential performance issues (see #23), so i don't think it will have any notable maintenance cost.

Do i have to add it myself, or is it sufficient to give you my blessing to go ahead?

**Comment by larstvei** [comment]
Great @phikal!

I read the rules, and can't see they wouldn't be satisfied.

Go ahead, and I'll close the issue. Thanks again :)
