### ISSUE TITLE
Face that `focus-unfocused` inherits from

### ISSUE THREAD

**Issue by phikal** [larstvei/Focus#27]
Hi,

currently `focus-unfocused` inherits from `font-lock-comment-face` which I get but might be suboptimal.  E.g. consider when focusing on a defun, and the defun begins with a comment.  Then the "unfocused" regions and the comment have the same color which might make it harder to draw a line when the comment is longer.

What do you think about inheriting from `shadow`, which might be the semantically more accurate face to use, since the intention is to "dim" the unfocused parts of the buffer?

**Comment by larstvei** [comment]
Yes, I completely agree! I simply was not aware of `shadow` face, which is a way better fit!

Thanks!
