### ISSUE TITLE
refresh buffer leaves everything unfocussed

### ISSUE THREAD

**Issue by fommil** [larstvei/Focus#4]
If I make a change to a buffer that has focus-mode enabled, and then refresh it (this is common when working with version control systems), the buffer remains completely unfocussed and must be explicitly disabled and enabled again.

**Comment by fommil** [comment]
workaround

```elisp
            (add-hook 'after-revert-hook (lambda ()
                                           (focus-mode 0)
                                           (focus-mode 1)))
```

**Comment by fommil** [comment]
workaround doesn't work :cry: only thing to do is to close the buffer entirely and reopen.

**Comment by larstvei** [comment]
Hi!

I was not able to reproduce the bug. What exactly do you mean by refresh? If you give me the name of the function that refreshes the buffer, I will hopefully be able to track down the bug.

**Comment by fommil** [comment]
Open a file like your init.El and make some changes in another editor. That usually triggers it for me.

**Comment by larstvei** [comment]
Ok, that sounds like `revert-buffer`. I tried using `revert-buffer` as well as making changes from another editor; I was still not able to reproduce the issue.

Could you check that you have an updated version of Focus (should be `0.1.0`)? It would be great if you could also tell me what version of Emacs and what OS you are using.

If you have a foolproof way of reproducing the error, please let me know. You can also check if the error occurs with the `-q` option enabled; if it does not, then there is probably something in your config that conflicts with `focus-mode`.

**Comment by fommil** [comment]
OK thanks for looking into this, I'll try to create a reproduction for you.

**Comment by fommil** [comment]
(Ping me if I forget, I'm into the whiskies now...)

**Comment by fommil** [comment]
ok, this is what I did:

1. opened up my `~/.emacs.d/init.el` https://github.com/fommil/dotfiles/blob/master/.emacs.d/init.el
2. went to about line 100, added some whitespace
3. `touch ~/.emacs.d/init.el`
4. back in emacs, `C-x C-s` then don't save. `reload-buffer`.
5. now nothing comes back in focus

**Comment by larstvei** [comment]
I followed the steps, but was still not able to reproduce... I have tried on Emacs `24.4`, `24.5` and `25`, but only with the most recent version of Focus.

Does the problem persist if you start emacs with `-q`? Have you checked the version of Focus? Sorry if I'm repeating myself.

In a previous version there was a problem with local variables getting killed; this can be triggered by switching mode. Try switching major mode and see if this triggers the problem; in that case an update should be sufficient.

**Comment by fommil** [comment]
Not at my computer, but I sync with MELPA dev branches every day so it'll be your master branch. Could well be an interaction with another minor mode. I'll try to minimise.

**Comment by fommil** [comment]
minimal (enough). Use this as your `~/.emacs.d/init.el` (most boilerplate to get `use-package` and MELPA into play)

```elisp
(require 'package)
(setq
 use-package-always-ensure t
 package-archives '(("melpa" . "http://melpa.org/packages/")))
(package-initialize)
(when (not package-archive-contents)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package)
(use-package focus
  :commands focus-mode)
(add-hook 'emacs-lisp-mode-hook
          (lambda()
            (focus-mode)))
```

put the point over one of the s-expressions and modify the buffer somehow, e.g. add a comment to the `use-package focus` block.

Then do a `M-x revert-buffer` (select `yes`).

I can no longer `focus` any s-expression other than the one I started with.


![focus-bug](https://cloud.githubusercontent.com/assets/1914041/12035901/d7c3d03e-ae38-11e5-8907-ee1a41fb766c.gif)

**Comment by larstvei** [comment]
Great, thanks!

The problem is that `focus-mode` will be called when it's already activated, due to it being on the hook (and reverting the buffer seems to trigger the hooks).

So the bug happens if you evaluate `(focus-mode 1)` twice.

Should be a quick fix, thanks for opening the issue!
